### ISSUE TITLE
通过set定义变量后，由于作用域问题无法修改变量

### ISSUE THREAD

**Issue by nx8823520** [kissyteam/xtemplate#54]
![image](https://cloud.githubusercontent.com/assets/1510980/5814835/c01ae368-a0ca-11e4-82c3-ddc793e2290a.png)
求解决方案，这样的变量场景还是很多的，如果if里面不能修改外围作用域变量，这样的话变量很多场景就失去了价值

**Comment by yiminghe** [comment]
需要实现类似 python 的方案

```
{{set(x=[0])}}
{{#each([1,2])}}
{{set(x[0] = x[0]+this)}}
{{/each}}
```

**Comment by dead-horse** [comment]
:beers:
